### ISSUE TITLE
Support For Face ID in Android is available?

### ISSUE THREAD

**Issue by Xor1980** [smstuebe/xamarin-fingerprint#158]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1.

2.

3.

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)

**Device:** e.g. HTC Sensation /i Phone 7 ...

**Comment by smsissuechecker** [comment]
Hi @Xor1980,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
Should be with version 2 see: 151

**Comment by YevhenVolynets** [comment]
@smstuebe I cannot see any code related to FaceId on Android. Is this feature are here?(> v 2.0). I have tested on the device which support FaceId but I saw only touch id feature.

**Comment by smstuebe** [comment]
@YevhenVolynets the plugin uses the biometric prompt api. I'll have a look into the API if it can be parameterized in a special way in order to support face unlock. Do you have more knowledge?

**Comment by Deepak1403** [comment]
I cannot see any code related to FaceId on Android, by default AuthenticationType returns fingerprint. Kindly provide any sample.

**Comment by smstuebe** [comment]
@Deepak1403 face id works out of the box, if the biometric authentication is setup to be face instead of fingerprint. Don't be confused by the Authentication type. This is du to the problem, that there was no API for finding out what the type is.

**Comment by Deepak1403** [comment]
Hi,

My biometric authentication is setup to be face instead of fingerprint but still not authenticated.
________________________________
From: Sven-Michael Stübe ***@***.***>
Sent: Thursday, May 6, 2021 4:26 PM
To: smstuebe/xamarin-fingerprint ***@***.***>
Cc: Ramesh, Deepak ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [smstuebe/xamarin-fingerprint] Support For Face ID in Android is available? (#158)


@Deepak1403 [github.com]<https://urldefense.com/v3/__https://github.com/Deepak1403__;!!A6SlFDHE!BmLPB6gsNrHVEDJTTnjpoDU4Vasr0_J6DHHQS7kQowSW9U_STRgJaFseq3g8MA$> face id works out of the box, if the biometric authentication is setup to be face instead of fingerprint. Don't be confused by the Authentication type. This is du to the problem, that there was no API for finding out what the type is.
