### ISSUE TITLE
Android SetConfirmationRequired

### ISSUE THREAD

**Issue by domagojmedo** [smstuebe/xamarin-fingerprint#192]
Is there a reason why SetConfirmationRequired is commented out in Android implementation.

https://github.com/smstuebe/xamarin-fingerprint/blob/0fc44bc84cf7a33d46f78fb34703c36d2e29a8ad/src/Plugin.Fingerprint/Platforms/Android/FingerprintImplementation.cs#L112

Would you be open to a PR that adds it as a property in config?

**Comment by smsissuechecker** [comment]
Hi @domagojmedo,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Yes because it was not supported by the AndroidX binding. I'll have a look if it's now available in the binding. I never checked it again after updating it.
And I'd need to check if there is a similar setting for iOS. I wanted to set it to false because this would be the same behavior as on iOS. And often the users of the plugin have struggles understanding, that some settings in the authentication configs are only available on some platforms - even if it's documented :/

Thanks for the hint.

**Comment by domagojmedo** [comment]
It's available in bindings now

**Comment by smstuebe** [comment]
It's in v2.1.2. Please give feedback

**Comment by domagojmedo** [comment]
It works 👍
