### ISSUE TITLE
unable to build ufter upgrading nuget to 1.3

### ISSUE THREAD

**Issue by nikolica** [smstuebe/xamarin-fingerprint#34]
The primary reference "Plugin.Fingerprint, Version=1.3.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Plugin.Fingerprint.Abstractions, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".

**Comment by smstuebe** [comment]
Try to update your VS and/or read: https://github.com/onovotny/Zeroconf/issues/60

**Comment by musterid** [comment]
I been having a very strange behavior for the passed week. So I had everything updated in VS2015 and the project was working fine. I installed the VS 2017 RC and everything broke. Since then I have uninstalled VS2017 but I get similar error

The primary reference "Plugin.Fingerprint, Version=1.3.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".

Anyone had this as well?

**Comment by nikolica** [comment]
I resolved the issue by following this: http://motzcod.es/post/148657853472/installing-a-pcl-into-netstandard-libraries and another issue is that xamarin studio (which i need to build ios version of the app) doesnt know how to handle this so i installed visual studio for mac and it works 🎉

**Comment by smstuebe** [comment]
Ye, I think its because I already switched to netstandard :) Sorry for being an early adopter :P

**Comment by kspearrin** [comment]
So we can't update to 1.3.0 without adding .NET Standard support to our App PCL?

**Comment by smstuebe** [comment]
@kspearrin: No, You can reference .net standard lubs from PCLs and vice versa. E.g. the Sample app is doing it. Please read about what .net standard is (https://docs.microsoft.com/de-de/dotnet/articles/standard/library#net-platforms-support) and update VS and everything else to the latest version.

**Comment by kspearrin** [comment]
@smstuebe I am running VS 2015 Update 3, fully up to date. Xamarin.Forms latest, PCL. Installing the nuget package for 1.3.0 does not allow the project to build, as mentioned in this issue.

The sample app does not seem to be using the nuget package (looks like a local reference), so it may be behaving differently. Please try the nuget package with a standard PCL project and you should see the issue.
